// docs/.vitepress/theme/components/HomeDemo.vue
<script setup>
import { ref, onMounted } from 'vue'
import { withBase } from 'vitepress'

const loaded = ref(false)
const failed = ref(false)

onMounted(() => {
  const img = new Image()
  img.src = withBase('/demo.gif')
  img.onload = () => { loaded.value = true }
  img.onerror = () => { failed.value = true }
})
</script>

<template>
  <section class="demo-section">
    <div class="section-inner">
      <p class="section-label">Demo</p>
      <h2 class="section-title">See it in action</h2>
      <p class="section-desc">Navigate your project, preview files, and manage everything from the terminal.</p>

      <div class="demo-window">
        <div class="demo-titlebar">
          <div class="demo-dot red"></div>
          <div class="demo-dot yellow"></div>
          <div class="demo-dot green"></div>
          <span>croot ~/project</span>
        </div>
        <div class="demo-content">
          <img v-if="loaded" :src="withBase('/demo.gif')" alt="croot demo showing file tree navigation, syntax preview, and git status" />
          <div v-else class="demo-placeholder">
            <p>$ croot <span class="cursor"></span></p>
            <p style="margin-top: 16px">Demo GIF is auto-generated on each release.</p>
            <p>Clone the repo and try it yourself!</p>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<style scoped>
.demo-section {
  background: var(--croot-bg);
  padding: 80px 24px;
  font-family: var(--croot-font-sans);
}

.section-inner {
  max-width: var(--croot-max-width);
  margin: 0 auto;
  text-align: center;
}

.section-desc {
  color: var(--croot-text-secondary);
  max-width: 600px;
  margin: 0 auto 48px;
  line-height: 1.6;
}

.demo-window {
  max-width: 840px;
  margin: 0 auto;
  border-radius: var(--croot-radius-md);
  overflow: hidden;
  border: 1px solid var(--croot-border);
  box-shadow: var(--croot-shadow-elevated);
}

.demo-titlebar {
  background: var(--croot-bg-elevated);
  padding: 12px 16px;
  display: flex;
  align-items: center;
  gap: 8px;
  border-bottom: 1px solid var(--croot-border);
}

.demo-dot {
  width: 12px;
  height: 12px;
  border-radius: 50%;
}

.demo-dot.red { background: #ff5f56; }
.demo-dot.yellow { background: #ffbd2e; }
.demo-dot.green { background: #27c93f; }

.demo-titlebar span {
  flex: 1;
  text-align: center;
  font-family: var(--croot-font-mono);
  font-size: 0.8rem;
  color: var(--croot-text-muted);
  margin-right: 44px;
}

.demo-content {
  background: #0d1117;
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 400px;
}

.demo-content img {
  width: 100%;
  display: block;
}

.demo-placeholder {
  color: #8b949e;
  font-family: var(--croot-font-mono);
  font-size: 0.85rem;
  text-align: center;
  padding: 40px;
}

.cursor {
  display: inline-block;
  width: 8px;
  height: 1.2em;
  background: #3fb950;
  vertical-align: text-bottom;
  animation: blink 1s step-end infinite;
}

@keyframes blink {
  50% { opacity: 0; }
}

@media (max-width: 640px) {
  .demo-section {
    padding: 60px 16px;
  }
}
</style>

// web/components/landing/HomeDemo.tsx
'use client'

import { useState, useEffect } from 'react'

export default function HomeDemo() {
  const [loaded, setLoaded] = useState(false)

  useEffect(() => {
    const img = new Image()
    img.src = '/croot/demo.gif'
    img.onload = () => setLoaded(true)
  }, [])

  return (
    <section
      style={{
        background: 'var(--croot-bg)',
        padding: '80px 24px',
        fontFamily: 'var(--croot-font-sans)',
      }}
    >
      <div style={{ maxWidth: 'var(--croot-max-width)', margin: '0 auto', textAlign: 'center' }}>
        <p
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: '0.35rem',
            padding: '0.35rem 0.7rem',
            border: '1px solid var(--croot-border)',
            borderRadius: 'var(--croot-radius-pill)',
            fontSize: 13,
            fontWeight: 500,
            color: 'var(--croot-text-muted)',
            background: 'var(--croot-bg-hover)',
            marginBottom: 12,
          }}
        >
          Demo
        </p>
        <h2
          style={{
            fontSize: 'clamp(1.5rem, 3vw, 2rem)',
            fontWeight: 700,
            marginBottom: 12,
            color: 'var(--croot-text)',
          }}
        >
          See it in action
        </h2>
        <p
          style={{
            color: 'var(--croot-text-secondary)',
            maxWidth: 600,
            margin: '0 auto 48px',
            lineHeight: 1.6,
          }}
        >
          Navigate your project, preview files, and manage everything from the
          terminal.
        </p>

        <div
          style={{
            maxWidth: 840,
            margin: '0 auto',
            borderRadius: 'var(--croot-radius-md)',
            overflow: 'hidden',
            border: '1px solid var(--croot-border)',
            boxShadow: 'var(--croot-shadow-elevated)',
          }}
        >
          <div
            style={{
              background: 'var(--croot-bg-elevated)',
              padding: '12px 16px',
              display: 'flex',
              alignItems: 'center',
              gap: 8,
              borderBottom: '1px solid var(--croot-border)',
            }}
          >
            <div style={{ width: 12, height: 12, borderRadius: '50%', background: '#ff5f56' }} />
            <div style={{ width: 12, height: 12, borderRadius: '50%', background: '#ffbd2e' }} />
            <div style={{ width: 12, height: 12, borderRadius: '50%', background: '#27c93f' }} />
            <span
              style={{
                flex: 1,
                textAlign: 'center',
                fontFamily: 'var(--croot-font-mono)',
                fontSize: '0.8rem',
                color: 'var(--croot-text-muted)',
                marginRight: 44,
              }}
            >
              croot ~/project
            </span>
          </div>
          <div
            style={{
              background: '#0d1117',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              minHeight: 400,
            }}
          >
            {loaded ? (
              <img
                src="/croot/demo.gif"
                alt="croot demo showing file tree navigation, syntax preview, and git status"
                style={{ width: '100%', display: 'block' }}
              />
            ) : (
              <div
                style={{
                  color: '#8b949e',
                  fontFamily: 'var(--croot-font-mono)',
                  fontSize: '0.85rem',
                  textAlign: 'center',
                  padding: 40,
                }}
              >
                <p>
                  $ croot{' '}
                  <span
                    style={{
                      display: 'inline-block',
                      width: 8,
                      height: '1.2em',
                      background: '#3fb950',
                      verticalAlign: 'text-bottom',
                      animation: 'blink 1s step-end infinite',
                    }}
                  />
                </p>
                <p style={{ marginTop: 16 }}>
                  Demo GIF is auto-generated on each release.
                </p>
                <p>Clone the repo and try it yourself!</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </section>
  )
}
